sudo: required
services:
  - docker

before_install:
  - docker build -t benwrighthd/frontend -f Dockerfile.dev .

script:
  - docker run benwrighthd/frontend yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'frontend'
  env: 'Frontend-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-051122044027'
  bucket_path: 'frontend'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
